services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
     - pgdata:/var/lib/postgresql
     - /home/the-grand-capybara/Desktop/Axiom/Projects/Managing-Sentry/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    image: php:8.2-cli
    environment:
     DB_HOST: db
     DB_PORT: 5432
     DB_NAME: ${DB_NAME}
     DB_USER: ${DB_USER}
     DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    working_dir: /app
    volumes:
      - /home/the-grand-capybara/Desktop/Axiom/Projects/Managing-Sentry/backend:/app
    ports:
      - "8000:8000"
    command: sh -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo_pgsql && apt-get clean && rm -rf /var/lib/apt/lists/* && php -S 0.0.0.0:8000"
    depends_on:
      - db

volumes:
  pgdata:
